<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Template' => 'Πρότυπο',
    'Templates' => 'Πρότυπα',
    'Template Types' => 'Τύποι Προτύπων',
    'Create' => 'Δημιουργία',
    'Create New Template' => 'Δημιουργία νέου προτύπου',
    'Update' => 'Αλλαγή',
    'Delete' => 'Διαγραφή',
    'Save' => 'Αποθήκευση',
    'Save Changes' => 'Αποθήκευση Αλλαγών',
    'ID' => 'ID Προτύπου',
    'Type' => 'Τύπος Προτύπου',
    'Description' => 'Περιγραφή',
    'Type Name' => 'Όνομα Τύπου',
    'Text' => 'Κείμενο',
    'Available Fields' => 'Διαθέσιμα Πεδία',
    'Are you sure you want to delete this item ?' => 'Είσαι σίγουρος πως θέλεις να διαγράψεις αυτό το αντικείμενο ?',
    '-- Select Value --' => '-- Επιλογή --',
    'Create Template' => 'Δημιουργία Προτύπου',
    'Create Template Type' => 'Δημιουργία Τύπου Προτύπου',
    'Template Type' => 'Τύπος Προτύπου',
    'Themes' => 'Θέματα',
    'Theme' => 'Θέμα',
    'Theme Name' => 'Όνομα Θέματος',
    'Upload' => 'Μεταφόρτωση',
    'Install' => 'Εγκατάσταση',
    'Upload and install new Theme' => 'Μεταφόρτωση και εγκατάσταση νέου Θέματος',
    'Environment' => 'Περιβάλλον',
    'Active' => 'Ενεργό',
    'Version' => 'Έκδοση',
    'Created At' => 'Δημιουργία',
    'Created By' => 'Δημιουργία από',
    'Updated At' => 'Αλλαγή',
    'Updated By' => 'Αλλαγή από',
    'View Template Type : ' => 'Εμφάνιση Τύπου Προτύπου : ',
    'Update Template type : ' => 'Εμφάνιση Τύπου Προτύπου : ',
    'View Template : ' => 'Εμφάνιση Προτύπου : ',
    'Update Template : ' => 'Αλλαγή Προτύπου : ',
    'Themes' => 'Θέματα',
    'View Theme : ' => 'Εμφάνιση Θέματος : ',
    'Copy' => 'Αντιγραφή',
    'View' => 'Εμφάνιση',
    'Delete Theme ! Are you sure ?' => 'Διαγραφή Θέματος ! Είσαι σίγουρος ?',
    'Theme : {name} is locked ! Cannot updated ! ' => 'Το Θέμα : {name} είναι κλειδωμένο ! Αλλαγή Αδύνατη ! ',
    'Theme name different from zip name !' => 'Το όνομα του Θέματος είναι διαφορετικό από το όνομα του zip αρχείου ! ',
    'Theme already exist !' => 'Το Θέμα υπάρχει ήδη ! ',
    'Theme cannot extract !' => 'Το Θέμα δεν μπορεί να αποσυμπιεστεί ! ',
    'Theme cannot Upload !' => 'Το Θέμα δεν μπορεί να μεταφορτωθεί ! ',
    'Theme {name} Uploaded !' => 'Το Θέμα {name} μεταφορτώθηκε ! ',
    'Theme cannot copy !' => 'Το Θέμα δεν μπορεί να αντιγραφεί ! ',
    'Theme : {name} created ! ' => 'Το Θέμα {name} δημιουργήθηκε ! ',
    'No Permission to Install Themes ' => 'Δεν έχετε το δικίωμα να εγκαταστήσετε Θέματα ! ',
    'No Permission to Create Theme ' => 'Δεν έχετε το δικίωμα να δημιουργήσετε Θέμα ! ',
    'No Permission to View Themes ' => 'Δεν έχετε το δικίωμα να δείτε τα Θέματα ! ',
    'Theme : {name} created ! ' => 'Το Θέμα : {name} δημιουργήθηκε ! ',
    'Theme : {name} deleted ! ' => 'Το Θέμα : {name} διαγράφηκε ! ',
    'Theme : {name} in use ! ' => 'Το Θέμα : {name} χρησιμοποιείται ! ',
    'Theme : {name} is locked ! Cannot Delete ! ' => 'Το Θέμα : {name} είναι κλειδωμένο, Διαγραφή αδύνατη ! ',
   
    
];
